export const authTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_FAILURE: "SIGNUP_FAILURE", // ON SIGNUP SUCCESS, LOGIN_SUCCESS IS DISPATCHED
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  VERIFY_REQUEST: "VERIFY_REQUEST",
  VERIFY_SUCCESS: "VERIFY_SUCCESS",
  APPLY_PROMOCODE_REQUEST: "APPLY_PROMOCODE_REQUEST",
  APPLY_PROMOCODE_SUCCESS: "APPLY_PROMOCODE_SUCCESS",
  APPLY_PROMOCODE_FAILURE: "APPLY_PROMOCODE_FAILURE",
  SET_USER_DATA: "SET_USER_DATA",
  SET_USER_TYPE: "SET_USER_TYPE",
  SET_ERRORS: "SET_ERRORS",
  CLEAR_ERRORS: "CLEAR_ERRORS",
  WANT_VERIFICATION_LINK: "WANT_VERIFICATION_LINK",
  SENT_VERIFICATION_LINK: "SENT_VERIFICATION_LINK",
  FAIL_VERIFICATION_LINK: "FAIL_VERIFICATION_LINK",
  PROFILE_UPDATE_REQUEST: "PROFILE_UPDATE_REQUEST",
  PROFILE_UPDATE_SUCCESS: "PROFILE_UPDATE_SUCCESS",
  PROFILE_UPDATE_ERROR: "PROFILE_UPDATE_ERROR",
  VERIFY_CRED_REQUEST: "VERIFY_CRED_REQUEST",
  VERIFY_CRED_SUCCESS: "VERIFY_CRED_SUCCESS",
  VERIFY_CRED_FAILURE: "VERIFY_CRED_FAILURE",
  DEACTIVATE_ACCOUNT_REQUEST: "DEACTIVATE_ACCOUNT_REQUEST",
  DEACTIVATE_ACCOUNT_SUCCESS: "DEACTIVATE_ACCOUNT_SUCCESS",
  DEACTIVATE_ACCOUNT_FAILURE: "DEACTIVATE_ACCOUNT_FAILURE",
  AUTH_DATA_REQUEST: "AUTH_DATA_REQUEST",
  AUTH_DATA_SUCCESS: "AUTH_DATA_SUCCESS",
  AUTH_DATA_FAILURE: "AUTH_DATA_FAILURE",
};

//Event types
export const EVENTS_PULL_REQUEST = "EVENTS_PULL_REQUEST";
export const EVENTS_PULL_SUCCESS = "EVENTS_PULL_SUCCESS";
export const EVENTS_PULL_FAILURE = "EVENTS_PULL_FAILURE";

export const EVENTS_BY_LOCATION_PULL_REQUEST =
  "EVENTS_BY_LOCATION_PULL_REQUEST";
export const EVENTS_BY_LOCATION_PULL_SUCCESS =
  "EVENTS_BY_LOCATION_PULL_SUCCESS";
export const EVENTS_BY_LOCATION_PULL_FAILURE =
  "EVENTS_BY_LOCATION_PULL_FAILURE";

//Vieing a business/ user page
export const USER_EVENTS_BY_LOCATION_PULL_REQUEST =
  "USER_EVENTS_BY_LOCATION_PULL_REQUEST";
export const USER_EVENTS_BY_LOCATION_PULL_SUCCESS =
  "USER_EVENTS_BY_LOCATION_PULL_SUCCESS";
export const USER_EVENTS_BY_LOCATION_PULL_FAILURE =
  "USER_EVENTS_BY_LOCATION_PULL_FAILURE";

export const CLEAR_USER_LOCATION_EVENT_DATA = "CLEAR_USER_LOCATION_EVENT_DATA";

export const CURRENT_EVENT_PULL_REQUEST = "CURRENT_EVENT_PULL_REQUEST";
export const CURRENT_EVENT_PULL_SUCCESS = "CURRENT_EVENT_PULL_SUCCESS";
export const CURRENT_EVENT_PULL_FAILURE = "CURRENT_EVENT_PULL_FAILURE";

export const SPECIFIED_EVENT_PULL_REQUEST_FB =
  "SPECIFIED_EVENT_PULL_REQUEST_FB";
export const SPECIFIED_EVENT_PULL_SUCCESS_FB =
  "SPECIFIED_EVENT_PULL_SUCCESS_FB";
export const SPECIFIED_EVENT_PULL_FAILURE_FB =
  "SPECIFIED_EVENT_PULL_FAILURE_FB";

export const SPECIFIED_EVENT_PULL_REQUEST_DB =
  "SPECIFIED_EVENT_PULL_REQUEST_DB";
export const SPECIFIED_EVENT_PULL_SUCCESS_DB =
  "SPECIFIED_EVENT_PULL_SUCCESS_DB";
export const SPECIFIED_EVENT_PULL_FAILURE_DB =
  "SPECIFIED_EVENT_PULL_FAILURE_DB";

export const USER_EVENT_PULL_REQUEST = "USER_EVENT_PULL_REQUEST";
export const USER_EVENT_PULL_SUCCESS = "USER_EVENT_PULL_SUCCESS";
export const USER_EVENT_PULL_FAILURE = "USER_EVENT_PULL_FAILURE";

export const CREATE_EVENT_REQUEST_FB = "CREATE_EVENT_REQUEST_FB";
export const CREATE_EVENT_SUCCESS_FB = "CREATE_EVENT_SUCCESS_FB";
export const CREATE_EVENT_FAILURE_FB = "CREATE_EVENT_FAILURE_FB";

export const CREATE_EVENT_REQUEST_DB = "CREATE_EVENT_REQUEST_DB";
export const CREATE_EVENT_SUCCESS_DB = "CREATE_EVENT_SUCCESS_DB";
export const CREATE_EVENT_FAILURE_DB = "CREATE_EVENT_FAILURE_DB";

export const UPDATE_EVENT_REQUEST_FB = "UPDATE_EVENT_REQUEST_FB";
export const UPDATE_EVENT_SUCCESS_FB = "UPDATE_EVENT_SUCCESS_FB";
export const UPDATE_EVENT_FAILURE_FB = "UPDATE_EVENT_FAILURE_FB";

export const UPDATE_EVENT_REQUEST_DB = "UPDATE_EVENT_REQUEST_DB";
export const UPDATE_EVENT_SUCCESS_DB = "UPDATE_EVENT_SUCCESS_DB";
export const UPDATE_EVENT_FAILURE_DB = "UPDATE_EVENT_FAILURE_DB";

export const CLEAR_ON_SUCCESSFUL_CREATE = "CLEAR_ON_SUCCESSFUL_CREATE";
export const CLEAR_ON_SUCCESSFUL_UPDATE = "CLEAR_ON_SUCCESSFUL_UPDATE";
export const CLEAN_EVENT_STATE = "CLEAN_EVENT_STATE"; //This one might be redundant now, remove.

// Product
export const PRODUCT_CATEGORY_PULL_REQUEST_DB  = "PRODUCT_CATEGORY_PULL_REQUEST_DB" 
export const PRODUCT_CATEGORY_PULL_SUCCESS_DB = "PRODUCT_CATEGORY_PULL_SUCCESS_DB"
export const PRODUCT_CATEGORY_PULL_FAILURE_DB  = "PRODUCT_CATEGORY_PULL_FAILURE_DB"

export const PRODUCT_PULL_REQUEST_DB  = "PRODUCT_PULL_REQUEST_DB" 
export const PRODUCT_PULL_SUCCESS_DB  = "PRODUCT_PULL_SUCCESS_DB" 
export const PRODUCT_PULL_FAILURE_DB  = "PRODUCT_PULL_FAILURE_DB" 


// product Report

export const REPORT_PRODUCT_REQUEST = "REPORT_PRODUCT_REQUEST"
export const REPORT_PRODUCT_SUCCESS = "REPORT_PRODUCT_SUCCESS"
export const REPORT_PRODUCT_FAILURE = "REPORT_PRODUCT_FAILURE"

//Pain types - Pulling other user data
export const VERIFY_USER_TYPE_REQUEST = "VERIFY_USER_TYPE_REQUEST";
export const VERIFY_USER_TYPE_SUCCESS = "VERIFY_USER_TYPE_SUCCESS";
export const VERIFY_USER_TYPE_FAILURE = "VERIFY_USER_TYPE_FAILURE";

export const ADD_FRIEND_FOLLOW_REQUEST = "ADD_FRIEND_FOLLOW_REQUEST";
export const ADD_FRIEND_FOLLOW_SUCCESS = "ADD_FRIEND_FOLLOW_SUCCESS";
export const ADD_FRIEND_FOLLOW_FAILURE = "ADD_FRIEND_FOLLOW_FAILURE";

export const BAD_SEARCH = "BAD_SEARCH";
export const CLEAR_USER = "CLEAR_USER";

// Dashboard
export const CLEAR_LOCATION_EVENT_DATA = "CLEAR_LOCATION_EVENT_DATA";



// Media
export const MEDIA_UPLOAD_REQUEST = "MEDIA_UPLOAD_REQUEST";
export const MEDIA_UPLOAD_PROCESSING = "MEDIA_UPLOAD_PROCESSING";
export const MEDIA_UPLOAD_COMPLETE = "MEDIA_UPLOAD_COMPLETE";
export const MEDIA_UPLOAD_FAILURE = "MEDIA_UPLOAD_FAILURE";

export const uiTypes = {
  TOGGLE_ALERT: "TOGGLE_ALERT",
  SET_UPDATE_AVAILABLE: "SET_UPDATE_AVAILABLE",
  CHECK_UPDATE_AVAILABLE: "CHECK_UPDATE_AVAILABLE",
  CLEAR_UPDATE_AVAILABLE: "CLEAR_UPDATE_AVAILABLE",

  ENQUEUE_SNACKBAR: "ENQUEUE_SNACKBAR",
  CLOSE_SNACKBAR: "CLOSE_SNACKBAR",
  REMOVE_SNACKBAR: "REMOVE_SNACKBAR",
  SEARCH_INITIAL: "SEARCH_INITIAL", // SEARCH BAR
  SEARCH_ADVANCE: "SEARCH_ADVANCE", // SEARCH BAR
  SEARCH_REQUEST: "SEARCH_REQUEST", // SEARCH PAGE
  SEARCH_FAILURE: "SEARCH_FAILURE", // SEARCH BAR AND PAGE
  SEARCH_BAR_COMPLETE: "SEARCH_BAR_COMPLETE",
  SEARCH_PAGE_COMPLETE: "SEARCH_PAGE_COMPLETE",
};
// Application wide
export const SET_UPDATE_AVAILABLE = "SET_UPDATE_AVAILABLE";
export const CHECK_UPDATE_AVAILABLE = "CHECK_UPDATE_AVAILABLE";
export const CLEAR_UPDATE_AVAILABLE = "CLEAR_UPDATE_AVAILABLE";

export const dashBoardTypes = {
  SET_DASHBOARD_LOCATION: "SET_DASHBOARD_LOCATION",
};
